---
title: 'APSTA 2047: HW1'
author: "William Spagnola & Emanuel Bazov"
date: "9/18/2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)

#fares <- read_csv("trip_fare_8.csv")
#trips <- read_csv("trip_data_8.csv")

```

```{r}

trips_hw_1  <- trips %>% filter(pickup_datetime >= ymd_hms("2013-08-15 00:00:00") 
                 & pickup_datetime < ymd_hms("2013-08-16 00:00:00"))

fares_hw_1 <- fares %>% filter(pickup_datetime >= ymd_hms("2013-08-15 00:00:00") 
                 & pickup_datetime < ymd_hms("2013-08-16 00:00:00"))


trips_hw_1 %>% arrange(desc(pickup_datetime))
trips_hw_1 %>% arrange(pickup_datetime)

fares_hw_1 %>% arrange(desc(pickup_datetime))
fares_hw_1 %>% arrange(pickup_datetime)


write_csv(x = trips_hw_1, path = "trips_hw_1.csv")
write_csv(x = fares_hw_1, path = "fares_hw_1.csv")

```


#Clean Data
```{r Clean}

trips_hw_1 <- read_csv("trips_hw_1.csv")



summary(trips_hw_1)


#Look at Trip Time 
trips_hw_1 %>%
      arrange(trip_time_in_secs)

#Filter Trips less than 60 seconds
trips_hw_1 <- trips_hw_1 %>% filter(trip_time_in_secs > 60)

#Generate column of trip time minutes
trips_hw_1 <- trips_hw_1 %>%
  mutate(trip_time_in_mins =  (trip_time_in_secs / 60)) 


#Generate column of trip time Hours
trips_hw_1 <- trips_hw_1 %>%
  mutate(trip_time_in_hrs =  (trip_time_in_mins / 60)) 

#Look at Max Trip Time in descending Order
trips_hw_1 %>%
      arrange(desc(trip_time_in_mins))
trips_hw_1 %>%
      arrange(desc(trip_time_in_hrs))

#Filter Trip Time to be less than or equal to 3 hours 
trips_hw_1 <- trips_hw_1 %>% 
  filter(trip_time_in_hrs  <= 3)
    
#Generate column of average speed
trips_hw_1 <- trips_hw_1 %>%
  mutate(avg_speed = trip_distance / (trip_time_in_secs / 3600)) 

#Examing Average Speed
summary(trips_hw_1$avg_speed)

#Filter Average Speed to be Less than or equal to 60
trips_hw_1 <- trips_hw_1 %>%
              filter(avg_speed <= 60)

#Filter Average Speed to be greater than or to 10
trips_hw_1 <- trips_hw_1 %>%
              filter(avg_speed >= 10)


#Check day  
trips_hw_1 %>%
  group_by(hack_license) %>%
  summarize(earliest_start=min(pickup_datetime)) %>%
  summarize(earliest_start = min(pickup_datetime), latest_finish = max(dropoff_datetime),
        workday_in_seconds = as.duration(latest_finish- earliest_start)) 


```


```{r}
fares_hw_1 <- read_csv("fares_hw_1.csv")

#Examining fare variables to see amounts that are unreasonable
summary(fares_hw_1)

#filter fare amounts less than $2.50 and unreasonably high fares. 
fares_hw_1<- fares_hw_1 %>%
  filter(fare_amount>2.5 & fare_amount<=200)

#Reexamining fare amounts. Looks Ok. 
summary(fares_hw_1$fare_amount)

#Boxplot to check surcharge distribution
boxplot(fares_hw_1$surcharge)

#filter out surcharges that are negative and too high
fares_hw_1<- fares_hw_1 %>%
   filter(surcharge>=0 & surcharge<367.46)

#Filter out 0s for MTA Tax
fares_hw_1<-fares_hw_1 %>%
  filter(mta_tax>0)

#Filter out tips greater than $100 and by tip amounts and imputed tip that differ by more than $1 
fares_hw_1<-fares_hw_1 %>%
  filter(tip_amount<100) %>% 
  mutate(imputed_tip=total_amount-(fare_amount+surcharge+mta_tax+tip_amount+tolls_amount))
fares_hw_1<-fares_hw_1 %>% 
  mutate(tip_diff = abs(imputed_tip - tip_amount), tip_diff_amount=abs(tip_diff-tip_amount)) %>% 
  filter(tip_diff_amount<1)

#Drop irrelevant columns
fares_hw_1<-fares_hw_1 %>%
  select(-tip_diff, -tip_diff_amount, -imputed_tip)


#Cleaning tolls by getting rid of amounts that are too high
fares_hw_1<- fares_hw_1%>%
  filter(tolls_amount<60)

#See how everything looks
summary(fares_hw_1)
```
